# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pedidos.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpedidos.proto\x12\x07pedidos\"O\n\x06Pedido\x12\x15\n\rnumero_pedido\x18\x01 \x01(\x05\x12\x0f\n\x07\x63liente\x18\x02 \x01(\t\x12\r\n\x05itens\x18\x03 \x03(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"J\n\x0eRespostaPedido\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x15\n\rnumero_pedido\x18\x03 \x01(\x05\"?\n\x11\x41tualizacaoStatus\x12\x15\n\rnumero_pedido\x18\x01 \x01(\x05\x12\x13\n\x0bnovo_status\x18\x02 \x01(\t\"H\n\x0cStatusPedido\x12\x15\n\rnumero_pedido\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"%\n\x0cNumeroPedido\x12\x15\n\rnumero_pedido\x18\x01 \x01(\x05\"\x07\n\x05Vazio2\x8e\x02\n\rPedidoService\x12:\n\x0c\x45nviarPedido\x12\x0f.pedidos.Pedido\x1a\x17.pedidos.RespostaPedido\"\x00\x12\x32\n\rReceberPedido\x12\x0e.pedidos.Vazio\x1a\x0f.pedidos.Pedido\"\x00\x12H\n\x0f\x41tualizarStatus\x12\x1a.pedidos.AtualizacaoStatus\x1a\x17.pedidos.RespostaPedido\"\x00\x12\x43\n\x0fMonitorarStatus\x12\x15.pedidos.NumeroPedido\x1a\x15.pedidos.StatusPedido\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pedidos_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PEDIDO._serialized_start=26
  _PEDIDO._serialized_end=105
  _RESPOSTAPEDIDO._serialized_start=107
  _RESPOSTAPEDIDO._serialized_end=181
  _ATUALIZACAOSTATUS._serialized_start=183
  _ATUALIZACAOSTATUS._serialized_end=246
  _STATUSPEDIDO._serialized_start=248
  _STATUSPEDIDO._serialized_end=320
  _NUMEROPEDIDO._serialized_start=322
  _NUMEROPEDIDO._serialized_end=359
  _VAZIO._serialized_start=361
  _VAZIO._serialized_end=368
  _PEDIDOSERVICE._serialized_start=371
  _PEDIDOSERVICE._serialized_end=641
# @@protoc_insertion_point(module_scope)
